constant:
  swagger-const:
    title: Odsay
    description: Server To Server Communication
    version: v0.1
odsay-api-conts:
  base-url: https://api.odsay.com/v1/api
  param-apk-key: apiKey
  param-api-key-value: GxXDL514Ds52H/04R8HPPo+2TZlcR7sQrmNnwb8+Sxw
  param-start-lqt-name: SY
  param-start-lng-name: SX
  param-end-lat-name: EY
  param-end-lng-name: EX

spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: false #open api에서 받은 json/xml에서 받고 싶지 않은 프로퍼티는 클래스를 만들 때 생략할 수 있게 해줌.
                                        #이 세팅을 안 하면 모든 프로퍼티를 클래스에 적어야 함

springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    operations-sorter: method
    path: /swagger
    tags-sorter: alpha
  cache:
    disabled: true

